name: Deploy Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Enable Corepack
        run: corepack enable
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: TypeScript Check
        run: pnpm run check
        
      - name: Build
        run: pnpm run build
        env:
          NODE_ENV: production
          SITE_URL: ${{ vars.SITE_URL }}
          GTM_ID: ${{ vars.GTM_ID }}
          GA_ID: ${{ vars.GA_ID }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
          retention-days: 1

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    needs: test  # 🔒 SAFETY GATE: Only run if tests pass!
    
    steps:
      - name: Environment Check
        run: |
          echo "🔍 Checking deployment configuration..."
          echo "Vercel configured: ${{ vars.VERCEL_PROJECT_ID != '' }}"
          echo "Netlify configured: ${{ vars.NETLIFY_SITE_ID != '' }}"
          echo "Site URL: ${{ vars.SITE_URL }}"
          
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-build
          path: dist/
          
      - name: Deploy to Netlify
        if: vars.NETLIFY_SITE_ID
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
        continue-on-error: true  # Don't fail entire deployment if one platform fails
          
      - name: Deploy to Vercel
        if: vars.VERCEL_PROJECT_ID
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
          PRODUCTION: true
        continue-on-error: false  # Fail if Vercel deployment fails (main platform)
          
      - name: Notify deployment success
        if: success()
        run: |
          echo "🚀 Production deployment successful!"
          echo "Site URL: ${{ vars.SITE_URL }}"
